bridge:
  type: multi_zmq_pub_bridge
  source_mode: zmq_source
  zmq_source_addr: tcp://127.0.0.1:4444
  result_pub_addr: tcp://0.0.0.0:8899
  result_pub_frame_id: camera_rgb_link
  result_siglip_topic: /siglip2/result
  result_siglip_vote_window: 5
  result_tf_topic: /tf
  robotaction:
    base_dir: configs/robotaction_data
    graph_info: graph_info
    test_box: test_box
    auto_run: true
    action_topic: /action
    status_topic: /siglip2/result
    progress_topic: /control/task_percentage
    object_tf_topic: /tf
  prompts:
    - toy car
sam3:
  server_addr: tcp://127.0.0.1:5562
  timeout_ms: 5000
flowpose:
  server_addr: tcp://127.0.0.1:6667
siglip2:
  server_addr: tcp://127.0.0.1:7777
