# Default initial positions for marvin_robot's ros2_control fake system

initial_positions:
  Joint1_L: 0
  Joint1_R: 0
  Joint2_L: 0
  Joint2_R: 0
  Joint3_L: 0
  Joint3_R: 0
  Joint4_L: 0
  Joint4_R: 0
  Joint5_L: 0
  Joint5_R: 0
  Joint6_L: 0
  Joint6_R: 0
  Joint7_L: 0
  Joint7_R: 0
  left_gripper_left_finger_joint: 0
  left_gripper_right_finger_joint: 0
  right_gripper_left_finger_joint: 0
  right_gripper_right_finger_joint: 0