# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    both_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - Joint1_L
      - Joint2_L
      - Joint3_L
      - Joint4_L
      - Joint5_L
      - Joint6_L
      - Joint7_L
    command_interfaces:
      []
    state_interfaces:
      []
right_arm_controller:
  ros__parameters:
    joints:
      - Joint1_R
      - Joint2_R
      - Joint3_R
      - Joint4_R
      - Joint5_R
      - Joint6_R
      - Joint7_R
    command_interfaces:
      []
    state_interfaces:
      []
both_arm_controller:
  ros__parameters:
    joints:
      - Joint1_L
      - Joint2_L
      - Joint3_L
      - Joint4_L
      - Joint5_L
      - Joint6_L
      - Joint7_L
      - left_gripper_left_finger_joint
      - left_gripper_right_finger_joint
      - Joint1_R
      - Joint2_R
      - Joint3_R
      - Joint4_R
      - Joint5_R
      - Joint6_R
      - Joint7_R
      - right_gripper_left_finger_joint
      - right_gripper_right_finger_joint
    command_interfaces:
      []
    state_interfaces:
      []